### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by ankonaskiff17** [dannymcgee/vscode-klipper#1]
Thank you for this. Makes my non-programmer life a bit easier.
Is there a way I can change some of the default colors within VS Code?
I am in no way a programmer but the HELP in VSC seems to imply you can tweak a json file within VS Code and I think the best way for me to describe is that I want to change the value or  entity to the right of the colon whether that is a pin number or some other value.

I found a project similar in some ways to Klipper called Magic Mirror, that uses Javascript modules and CSS to make custom displays and I learned the value of using color for readability building MM's.
When I asked about formatting the text on the Klipper Discord it drew a blank. Shortly thereafter I found your extension which I have put to use so again, thank you.

**Comment by dannymcgee** [comment]
Thanks for the kind words!

The extension does assign a unique TextMate grammar scope for pin IDs, which you can see by opening the command palette (Ctrl/Cmd+Shift+P) and running **Developer: Inspect Editor Tokens and Scopes**.

Currently for something like this:
```
data_pin: rpi:gpio10
```
* `rpi` gets a scope of `entity.name.class.kipper-cfg`
* `gpio10` gets `variable.other.enummember.klipper-cfg`
* The whole value (`rpi:gpio10`) is wrapped with a scope of `meta.pin-id.klipper-cfg`

IIRC you can override your theme's colors for specific TM scopes, but I'm not really sure how to do that off the top of my head, I'd recommend searching the VS Code docs.
